"""
Swarm Models Package
Export all swarm-related models for easy importing.
"""

from app.swarm.models.agent import (
    Agent,
    AgentCreate,
    AgentHeartbeat,
    AgentMetrics,
    AgentResponse,
    AgentState,
    AgentType,
    AgentUpdate,
)
from app.swarm.models.loop import (
    BacklogItem,
    ExecutiveSummary,
    Loop,
    LoopConfig,
    LoopCreate,
    LoopMetrics,
    LoopResponse,
    LoopState,
    STUFEStage,
    STUFETransition,
    SwarmStatusBoard,
    UltraScorecard,
)
from app.swarm.models.mutation import (
    ABTestConfig,
    ABTestResult,
    Mutation,
    MutationCreate,
    MutationEvaluation,
    MutationResponse,
    MutationSearchParams,
    MutationState,
    MutationType,
)
from app.swarm.models.prompt import (
    Prompt,
    PromptCreate,
    PromptHealth,
    PromptResponse,
    PromptSearchParams,
    PromptState,
    PromptType,
    PromptUpdate,
    PromptUsageRecord,
)
from app.swarm.models.swarm import (
    Swarm,
    SwarmConfig,
    SwarmCreate,
    SwarmMetrics,
    SwarmResponse,
    SwarmState,
    SwarmStatus,
    SwarmType,
    SwarmUpdate,
)
from app.swarm.models.task import (
    Task,
    TaskAssignment,
    TaskCreate,
    TaskPriority,
    TaskResponse,
    TaskResult,
    TaskSearchParams,
    TaskState,
    TaskType,
    TaskUpdate,
)

__all__ = [
    # Agent models
    "Agent",
    "AgentCreate",
    "AgentHeartbeat",
    "AgentMetrics",
    "AgentResponse",
    "AgentState",
    "AgentType",
    "AgentUpdate",
    # Loop models
    "BacklogItem",
    "ExecutiveSummary",
    "Loop",
    "LoopConfig",
    "LoopCreate",
    "LoopMetrics",
    "LoopResponse",
    "LoopState",
    "STUFEStage",
    "STUFETransition",
    "SwarmStatusBoard",
    "UltraScorecard",
    # Mutation models
    "ABTestConfig",
    "ABTestResult",
    "Mutation",
    "MutationCreate",
    "MutationEvaluation",
    "MutationResponse",
    "MutationSearchParams",
    "MutationState",
    "MutationType",
    # Prompt models
    "Prompt",
    "PromptCreate",
    "PromptHealth",
    "PromptResponse",
    "PromptSearchParams",
    "PromptState",
    "PromptType",
    "PromptUpdate",
    "PromptUsageRecord",
    # Swarm models
    "Swarm",
    "SwarmConfig",
    "SwarmCreate",
    "SwarmMetrics",
    "SwarmResponse",
    "SwarmState",
    "SwarmStatus",
    "SwarmType",
    "SwarmUpdate",
    # Task models
    "Task",
    "TaskAssignment",
    "TaskCreate",
    "TaskPriority",
    "TaskResponse",
    "TaskResult",
    "TaskSearchParams",
    "TaskState",
    "TaskType",
    "TaskUpdate",
]
